version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:nokib@database:5432/postgres?schema=public
    volumes:
      - './src:/usr/src/app/src'
    depends_on:
      - database

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nokib
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    # volumes:
    #   - 'C:/Program Files/PostgreSQL/16/data:/var/lib/postgresql/data'
