apiVersion: v1 
kind: Service
metadata:
  name: npest
  labels:
    app: npest
spec:
  selector:
    app: npest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
  externalIPs:
    - 172.19.0.3